{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: {{ .Values.ingress.tlsIssuer }}
spec:
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Chart.Name }}-tls
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /monitoring
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.monitoring.grafanaServiceName }}
            port:
              number: {{ .Values.monitoring.grafanaPort }}
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.monitoring.grafanaServiceName }}
            port:
              number: {{ .Values.monitoring.grafanaPort }}
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Chart.Name }}-service
            port:
              number: {{ .Values.service.port }}
{{- end }}
