name: mlops_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  # ML & API
  - scikit-learn
  - pandas
  - joblib
  - fastapi
  - uvicorn
  - requests
  - jupyter
  # Infra tools (available in Conda)
  - terraform
  - ansible
  - pip:
      - prometheus-client
