apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: fraudapp-encryption-prod
spec:
  acme:
    email: e.vutla1@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: fraudapp-encryption-prod
    solvers:
    - http01:
        ingress:
          class: nginx
