apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
spec:
  type: LoadBalancer   # exposes a public IP in AKS
  selector:
    app: fraud-api
  ports:
    - port: 80        # external port
      targetPort: 8000
