---
# Source: fraud-api/templates/Service.yaml
apiVersion: v1
kind: Service
metadata:
  name: fraud-api-service
  labels:
    app: fraud-api
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: fraud-api
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
---
# Source: fraud-api/templates/Deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-api
  labels:
    app: fraud-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fraud-api
  template:
    metadata:
      labels:
        app: fraud-api
    spec:
      containers:
        - name: fraud-api
          image: "mlopsdevacr2025.azurecr.io/fraud-api:0.1.5"
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MODEL_PATH
              value: "model/pipeline.joblib"
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
# Source: fraud-api/templates/Ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraud-api-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: fraudapp-encryption-prod
spec:
  tls:
  - hosts:
      - fraud-api.myapp.it.com
    secretName: fraud-api-tls
  rules:
  - host: fraud-api.myapp.it.com
    http:
      paths:
      - path: /monitoring
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
      - path: /login
        pathType: Prefix
        backend:
          service:
            name: prometheus-grafana
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fraud-api-service
            port:
              number: 80
